env              = "dev"
instance_type    = "t2.micro"
max_size         = 5
min_size         = 2
desired_capacity = 3
force_delete     = true
region           = "ue1"
stage            = "nonprod"
project          = "Ctask"
ingress_ports    = ["22", "80"]
